version: "3.9"
services:
  subscription-service:
    build: ./subscription-service
    ports:
      - 8081:8081
    environment:
      - JDBC_PASSWORD={DB_PASSWORD}
      - SUBSCRIPTION_SERVICE_HOST=subscription-service
    depends_on:
      db:
        condition: service_healthy
  user-service:
    build: ./user-service
    ports:
      - 8082:8082
    environment:
      - JDBC_PASSWORD={DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    volumes:
      - ./pg_data:/var/lib/postgresql
      - ./docker-entrypoint-initdb.d/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5